name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check git version
        run: git --version

      - name: print message
        run: echo "hello github actions"
